#!/usr/bin/env bash
# Sign this machine in to GitHub. Nothing secret is ever stored in the repo:
# credentials are generated or issued per machine rather than synced, which is
# better hygiene and means this repo can be public.
#
#   ./scripts/secrets-setup.sh          gh auth login (HTTPS + token)
#   ./scripts/secrets-setup.sh --ssh    also generate ~/.ssh/id_ed25519
#
# AUTHENTICATION HERE IS HTTPS + PERSONAL ACCESS TOKEN, NOT SSH.
#
# Both remotes are cloned over HTTPS - github.com and the private forge - and
# both authenticate with a PAT held in the desktop keyring. That is what
# scripts/git-credentials.sh sets up, and it is the path to follow; this script
# only covers the `gh` CLI's own session, which is likewise HTTPS + token.
#
# No SSH key is generated by default, because nothing in this repo uses one: no
# remote is an SSH URL, dot_gitconfig.tmpl has no url-rewrite rules, and
# doctor.sh does not check for a key. Generating one by reflex left a key on
# disk that was never added to any host - so it is opt-in behind --ssh, for the
# day a host actually requires it.
set -uo pipefail
cd "$(dirname "$0")/.."
. lib/log.sh

WANT_SSH=0
while [ $# -gt 0 ]; do case "$1" in
  --ssh)     WANT_SSH=1 ;;
  -h|--help) awk 'NR>1 { if (!/^#/) exit; sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
  *)         die "unknown flag: $1" ;;
esac; shift; done

banner "secrets" "sign in to GitHub - HTTPS and a token, not SSH"

step "GitHub CLI"
if command -v gh >/dev/null; then
  if gh auth status >/dev/null 2>&1; then
    ok "gh already authenticated"
  else
    info "choose HTTPS when it asks for the git protocol"
    gh auth login
  fi
else
  warn "gh not installed"
fi

if [ "$WANT_SSH" -eq 1 ]; then
  EMAIL=$(git config --global user.email 2>/dev/null || true)
  [ -n "$EMAIL" ] || read -r -p "Email for the SSH key: " EMAIL

  step "SSH key (--ssh)"
  if [ -f "$HOME/.ssh/id_ed25519" ]; then
    ok "~/.ssh/id_ed25519 already exists"
  else
    ssh-keygen -t ed25519 -C "$EMAIL" -f "$HOME/.ssh/id_ed25519" && ok "key generated"
  fi
  info "Public key - add at https://github.com/settings/keys"
  cat "$HOME/.ssh/id_ed25519.pub"
  warn "a key alone changes nothing: remotes stay HTTPS until you rewrite them."
fi

step "Next - this is the step that stops the prompts"
cat <<'EOS'
  ./scripts/git-credentials.sh   a Personal Access Token per host - github.com
                                 and your private forge - handed to git's
                                 credential helper and kept in the keyring.
                                 HTTPS git stops asking on every fetch and push.
EOS

step "Not managed here (by design)"
cat <<'EOS'
  ~/.npmrc, ~/.nuget/NuGet.Config   registry tokens
  ~/.docker/config.json             registry credentials
  kwallet                           desktop secrets. On Plasma it is ksecretd that
                                    owns org.freedesktop.secrets, NOT gnome-keyring -
                                    which is why git-credentials.sh works here
  Brave profile                     use Brave Sync (a sync chain, not an account)
  Bitwarden vault                   sign in normally
EOS
steps_end
